spring.config.import=optional:file:./.env[.properties]
spring.application.name=backend

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

security.jwt.secret=${JWT_SECRET}
security.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS:3600}
